export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'

export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const DEFAULT_NOTIF = 'default'

export const SET_NOTE_DATA = 'SET_NOTE_DATA'

export const SET_NOTE_LIST = 'SET_NOTE_LIST'

export const SET_TAG_LIST = 'SET_TAG_LIST'

export const SET_FOLDER_LIST = 'SET_FOLDER_LIST'

export const ADD_FOLDER = 'ADD_FOLDER'

export const UPDATE_NOTE_LIST = 'UPDATE_NOTE_LIST'

export const SET_FOLDER_DATA = 'SET_FOLDER_DATA'

export const SET_NAVIGATION_UPDATE = 'SET_NAVIGATION_UPDATE'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'

export const ADD_FAVORITE = 'ADD_FAVORITE'

export const DELETE_FAVORITE = 'DELETE_FAVORITE'

export const DELETE_NOTE_LIST = 'DELETE_NOTE_LIST'
